2022-07-25 21:12:42,739 - pyswarms.single.global_best - INFO - Optimize for 50 iters with {'c1': 0.9, 'c2': 0.1, 'w': 0.9}
2022-07-25 21:12:43,744 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 0.0005398000256080532, best pos: [-0.69336975 -0.3490242  -1.4561913  -2.2691984  -1.18372301 -0.83059122
 -1.41912892 -0.48013515 -1.04731063 -0.89128579 -1.50178736 -0.51673518
 -0.44822493 -0.12865276 -1.75126619 -1.31048548 -1.17142881 -1.0241611
 -0.65787628 -1.27481452 -0.64752131 -0.2366138  -0.48249704 -0.89603585
 -1.55462858 -0.45978331 -1.00041844  0.19198802 -0.96747413 -0.74441925
 -2.35553735 -1.61486788 -0.29058695 -0.89250563 -0.25225605 -2.24939935
  0.0610376  -1.68055449  0.14481084  0.469257   -1.81277299 -1.27512067
 -1.18189072 -0.65131426 -1.17692329 -0.85271204 -1.18024491 -1.04833745
 -1.26522676 -0.29118293 -1.07414017 -0.98068406 -1.28310278 -1.55959107
 -0.35710705  0.09946518 -2.07682886  0.1919977  -0.29390342 -1.73974532
 -1.25561373 -0.94086659 -0.90356952 -0.81537347 -0.35462355 -1.02800569
 -2.20426947 -0.63999352 -0.45081896 -0.53881398 -1.1540402  -0.82836479
 -0.20714892 -0.0617963  -1.60229802 -0.70585134 -0.6175651  -1.6139681
  0.11204732 -1.01865331 -0.41995907 -0.33986973 -0.63664142 -1.22071999
 -1.28553483 -0.5634307  -1.01794045 -1.14686539 -0.26791181 -0.68628836
 -0.94182163 -0.75110571 -0.31510848  0.35707795 -0.81136412 -0.54132489
 -0.3571276  -0.31303312 -2.25682779 -2.18629131 -0.89404737 -0.34961407
 -0.52253684 -0.9313972  -0.10684207 -1.44324714 -0.79131981  0.01315534
 -0.58405588 -0.97913267 -0.15768407 -0.00596258 -1.115624   -1.96140493
 -0.42687792 -0.90895114 -1.34379525  0.18530011 -1.4394025   0.06363433
 -0.69991004 -0.80000404 -1.02446463 -0.88714703 -0.44449672 -1.35795079
 -1.40022292 -1.06072892  0.15074994 -0.87137659 -0.7151776  -0.12103707
 -1.99854461 -1.55604793 -0.70015741 -1.8124574  -1.76645776 -1.27000037
 -0.67311863 -1.22219929 -0.31478553 -0.97378604 -1.16433887 -1.70029937
 -0.52922374 -0.61536105 -0.93670722 -1.37691509 -0.86528696 -0.31060783
 -0.69521872  0.04364449 -1.60658663 -0.76936201 -0.63750575 -0.51979648
 -0.32936263 -2.65308271 -1.03451576 -1.46666347  0.08680913 -1.04870775
 -0.97995222 -1.06605236 -1.39227826 -1.61445429 -0.74359078 -0.32103528
 -0.50288329 -1.61252362 -1.12175701 -0.49488414 -2.1144967  -0.00901277
 -0.4110069   0.14305088 -2.87104689 -1.01988364 -1.38520326 -2.0687873
 -0.26895214]
2022-07-25 21:12:43,755 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 21:12:43] "[37mGET /nnsoh HTTP/1.1[0m" 200 -
2022-07-25 21:12:50,371 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 21:12:50] "[37mGET /nnsoc HTTP/1.1[0m" 200 -
2022-07-25 21:13:06,863 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 21:13:06] "[37mGET /l2soh HTTP/1.1[0m" 200 -
2022-07-25 21:13:17,074 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 21:13:17] "[37mGET /l2soc HTTP/1.1[0m" 200 -
2022-07-25 21:13:25,839 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 21:13:25] "[37mGET /mlstmsoh HTTP/1.1[0m" 200 -
2022-07-25 21:13:29,573 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 21:13:29] "[37mGET /mlstmsoc HTTP/1.1[0m" 200 -
2022-07-25 21:14:58,816 - app - ERROR - Exception on /gasoh [GET]
Traceback (most recent call last):
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 455, in gasoh
    modelGAsoh=load_model('modelGASOH.h5')
  File "/home/dell/anaconda3/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/dell/anaconda3/lib/python3.7/site-packages/keras/saving/save.py", line 212, in load_model
    'Filepath looks like a hdf5 file but h5py is not available.'
ImportError: Filepath looks like a hdf5 file but h5py is not available. filepath=modelGASOH.h5
2022-07-25 21:14:58,818 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 21:14:58] "[35m[1mGET /gasoh HTTP/1.1[0m" 500 -
2022-07-25 21:16:54,070 - app - ERROR - Exception on /gasoh [GET]
Traceback (most recent call last):
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dell/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 455, in gasoh
    modelGAsoh=load_model('modelGASOH.h5')
  File "/home/dell/anaconda3/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/dell/anaconda3/lib/python3.7/site-packages/keras/saving/save.py", line 212, in load_model
    'Filepath looks like a hdf5 file but h5py is not available.'
ImportError: Filepath looks like a hdf5 file but h5py is not available. filepath=modelGASOH.h5
2022-07-25 21:16:54,071 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 21:16:54] "[35m[1mGET /gasoh HTTP/1.1[0m" 500 -
2022-07-25 22:23:06,749 - pyswarms.single.global_best - INFO - Optimize for 50 iters with {'c1': 0.9, 'c2': 0.1, 'w': 0.9}
2022-07-25 22:23:07,914 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 0.0005398000256080532, best pos: [-0.69336975 -0.3490242  -1.4561913  -2.2691984  -1.18372301 -0.83059122
 -1.41912892 -0.48013515 -1.04731063 -0.89128579 -1.50178736 -0.51673518
 -0.44822493 -0.12865276 -1.75126619 -1.31048548 -1.17142881 -1.0241611
 -0.65787628 -1.27481452 -0.64752131 -0.2366138  -0.48249704 -0.89603585
 -1.55462858 -0.45978331 -1.00041844  0.19198802 -0.96747413 -0.74441925
 -2.35553735 -1.61486788 -0.29058695 -0.89250563 -0.25225605 -2.24939935
  0.0610376  -1.68055449  0.14481084  0.469257   -1.81277299 -1.27512067
 -1.18189072 -0.65131426 -1.17692329 -0.85271204 -1.18024491 -1.04833745
 -1.26522676 -0.29118293 -1.07414017 -0.98068406 -1.28310278 -1.55959107
 -0.35710705  0.09946518 -2.07682886  0.1919977  -0.29390342 -1.73974532
 -1.25561373 -0.94086659 -0.90356952 -0.81537347 -0.35462355 -1.02800569
 -2.20426947 -0.63999352 -0.45081896 -0.53881398 -1.1540402  -0.82836479
 -0.20714892 -0.0617963  -1.60229802 -0.70585134 -0.6175651  -1.6139681
  0.11204732 -1.01865331 -0.41995907 -0.33986973 -0.63664142 -1.22071999
 -1.28553483 -0.5634307  -1.01794045 -1.14686539 -0.26791181 -0.68628836
 -0.94182163 -0.75110571 -0.31510848  0.35707795 -0.81136412 -0.54132489
 -0.3571276  -0.31303312 -2.25682779 -2.18629131 -0.89404737 -0.34961407
 -0.52253684 -0.9313972  -0.10684207 -1.44324714 -0.79131981  0.01315534
 -0.58405588 -0.97913267 -0.15768407 -0.00596258 -1.115624   -1.96140493
 -0.42687792 -0.90895114 -1.34379525  0.18530011 -1.4394025   0.06363433
 -0.69991004 -0.80000404 -1.02446463 -0.88714703 -0.44449672 -1.35795079
 -1.40022292 -1.06072892  0.15074994 -0.87137659 -0.7151776  -0.12103707
 -1.99854461 -1.55604793 -0.70015741 -1.8124574  -1.76645776 -1.27000037
 -0.67311863 -1.22219929 -0.31478553 -0.97378604 -1.16433887 -1.70029937
 -0.52922374 -0.61536105 -0.93670722 -1.37691509 -0.86528696 -0.31060783
 -0.69521872  0.04364449 -1.60658663 -0.76936201 -0.63750575 -0.51979648
 -0.32936263 -2.65308271 -1.03451576 -1.46666347  0.08680913 -1.04870775
 -0.97995222 -1.06605236 -1.39227826 -1.61445429 -0.74359078 -0.32103528
 -0.50288329 -1.61252362 -1.12175701 -0.49488414 -2.1144967  -0.00901277
 -0.4110069   0.14305088 -2.87104689 -1.01988364 -1.38520326 -2.0687873
 -0.26895214]
2022-07-25 22:23:07,929 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 22:23:07] "[37mGET /nnsoh HTTP/1.1[0m" 200 -
2022-07-25 22:23:09,988 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 22:23:09] "[37mGET /models HTTP/1.1[0m" 200 -
2022-07-25 22:23:11,556 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 22:23:11] "[37mGET /nnsoc HTTP/1.1[0m" 200 -
2022-07-25 22:23:18,911 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 22:23:18] "[37mGET /models HTTP/1.1[0m" 200 -
2022-07-25 22:23:20,955 - tensorflow - WARNING - AutoGraph could not transform <function Model.make_predict_function.<locals>.predict_function at 0x7fd8c0a74680> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
2022-07-25 22:23:21,237 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 22:23:21] "[37mGET /gasoh HTTP/1.1[0m" 200 -
2022-07-25 22:23:29,150 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 22:23:29] "[37mGET /models HTTP/1.1[0m" 200 -
2022-07-25 22:23:30,915 - tensorflow - WARNING - AutoGraph could not transform <function Model.make_predict_function.<locals>.predict_function at 0x7fd8c019da70> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
2022-07-25 22:23:31,206 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 22:23:31] "[37mGET /gasoc HTTP/1.1[0m" 200 -
2022-07-25 22:23:36,685 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 22:23:36] "[37mGET /graph HTTP/1.1[0m" 200 -
2022-07-25 22:23:44,057 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 22:23:44] "[37mGET /aboutUs HTTP/1.1[0m" 200 -
2022-07-25 22:23:46,027 - werkzeug - INFO - 127.0.0.1 - - [25/Jul/2022 22:23:46] "[37mGET / HTTP/1.1[0m" 200 -
